/** AliensVsPredator - Copyright (C) 2012-2015 Arisux **/
package com.arisux.avp;

import java.util.Arrays;

import com.arisux.airi.AIRI;
import com.arisux.airi.api.updater.Updater;
import com.arisux.avp.api.WristbracerAPI;

import cpw.mods.fml.common.FMLCommonHandler;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.event.*;
import cpw.mods.fml.relauncher.Side;

@Mod(modid = Properties.ID, name = Properties.NAME, version = Properties.VERSION, dependencies = "required-after:AIRI;", canBeDeactivated = true)
public class AliensVsPredator
{
	@Mod.Instance(Properties.ID)
	public static AliensVsPredator INSTANCE;

	public Properties properties = new Properties();
	public LocalEventHandler localEvents;
	public NetworkHandler network;
	public KeybindHandler keybinds;
	public EntityHandler entities;
	public CreativeTab tab;
	public BlockHandler blocks;
	public ItemHandler items;
	public WorldGenHandler worldgen;
	public CraftingHandler crafting;
	public GuiHandler guis;
	public RenderingHandler renderer;
	public DimensionHandler dimensions;
	public CommandHandler commands;
	public Settings settings;
	public Updater updater;
	public APIHandler apis = new APIHandler();
	
	public class APIHandler
	{
		public WristbracerAPI wristbracerApi;
		
		public APIHandler()
		{
			if (FMLCommonHandler.instance().getSide() == Side.CLIENT)
			{
				this.wristbracerApi = new WristbracerAPI();
			}
		}
	}
	
	@Mod.EventHandler
	public void preInitialize(FMLPreInitializationEvent event)
	{
		(settings = new Settings()).preInitialize(event);

		event.getModMetadata().autogenerated = false;
		event.getModMetadata().modId = Properties.ID;
		event.getModMetadata().name = Properties.NAME;
		event.getModMetadata().version = Properties.VERSION;
		event.getModMetadata().credits = "The Minecraft Community";
		event.getModMetadata().authorList = Arrays.asList("Ri5ux", "Ieuan");
		event.getModMetadata().description = "Contains content from several movie series, including the Alien, Predator, Aliens Vs Predator, and Prometheus series. The mod adds countless blocks, items, and mobs to the world of Minecraft for you to start Building Better Worlds(TM). ";
		event.getModMetadata().url = properties.SERVER_ADDRESS + "/page/mods/aliensvspredator/";
		event.getModMetadata().updateUrl = properties.SERVER_ADDRESS + "/page/mods/aliensvspredator/";
		event.getModMetadata().screenshots = new String[0];
		event.getModMetadata().logoFile = "";
	}

	@Mod.EventHandler
	public void initialize(FMLInitializationEvent event)
	{
		AIRI.logger.info("AliensVsPredator - Copyright(C) 2012-2015 Arisux");
		
		(tab = new CreativeTab()).initialize();
		(items = new ItemHandler()).initialize();
		(blocks = new BlockHandler()).initialize();
		(network = new NetworkHandler()).initialize();
		(dimensions = new DimensionHandler()).initialize();
		(entities = new EntityHandler()).initialize();
		(worldgen = new WorldGenHandler()).initialize();
		(crafting = new CraftingHandler()).initialize();
		(guis = new GuiHandler()).initialize();
		(localEvents = new LocalEventHandler()).initialize();
		(commands = new CommandHandler()).initialize();
		
		if (FMLCommonHandler.instance().getSide() == Side.CLIENT)
		{
			(keybinds = new KeybindHandler()).initialize();
			(renderer = new RenderingHandler()).initialize();

			if (settings.updaterEnabled)
			{
				(updater = AIRI.instance().updaterapi.createNewUpdater(Properties.NAME, Properties.VERSION, settings.updateStringUrl, properties.URL_MODPAGE, properties.URL_CHANGELOG)).initialize();
			}
		}
	}
	
	@Mod.EventHandler
	public void onServerStart(FMLServerStartingEvent event)
	{
		this.commands.onServerStart(event);
	}

	public boolean isBetaRelease()
	{
		return true;
	}
}